### PR TITLE
chore: converted final files

### PR DESCRIPTION
**Pull request by Goldziher**
This PR converts the last few files to typescript. These were particularly full of TS issues, so I set them aside previously.

### CODE REVIEW

**Comment by umodoc** [comment]
We have made many modifications to your submitted PR to ensure the project runs correctly (https://github.com/umodoc/editor/commit/22c182ed74092e4f5285cbd17a0215a76413cfa8). This includes simplifying some method calls. However, we haven't done detailed testing yet, including the changes we made. The testing might be done later, possibly much later, as we are currently busy with other work. If you have time, you could start some testing first.

Could you please help us calibrate the translation files? As we are Chinese developers with limited English proficiency, most of the translation content was done through AI and may contain errors or inaccuracies. The calibration is not limited to the keys and values in the translation files. We greatly appreciate your assistance!

**Comment by Goldziher** [comment]
as for [22c182e](https://github.com/umodoc/editor/commit/22c182ed74092e4f5285cbd17a0215a76413cfa8) -- you reverted some files back to being JS files. This is a step in the wrong direction in general. 

As for autoimports - I think this makes the code much harder to reason about, and some tooling doesn't work properly with it. It certainly saves on some code, but I try to avoid these kind of clever tricks. Maybe I'm just too much of a backend engineer

**Comment by umodoc** [comment]
The changes were made to fix a startup error and get the project running. We didn't delve into other issues at the time.

Feel free to suggest better solutions or make further edits.

**Comment by umodoc** [comment]
> > We have made many modifications to your submitted PR to ensure the project runs correctly ([22c182e](https://github.com/umodoc/editor/commit/22c182ed74092e4f5285cbd17a0215a76413cfa8)). This includes simplifying some method calls. However, we haven't done detailed testing yet, including the changes we made. The testing might be done later, possibly much later, as we are currently busy with other work. If you have time, you could start some testing first.
> > 
> > Could you please help us calibrate the translation files? As we are Chinese developers with limited English proficiency, most of the translation content was done through AI and may contain errors or inaccuracies. The calibration is not limited to the keys and values in the translation files. We greatly appreciate your assistance!
> 
> For now my work on editors has been paused - I just wanted to finish this PR since I already started, and it is my hope that you fellows will continue the testing to make it comprehensive and more stable. If in the end we decide to continue building an editor (which is not certain at present), and I decide this editor is sufficiently stable, I will gladly contribute this. I appreciate your openness to incorporating changes, its very refreshing. You can contact me via email (nhirschfeld@gmail.com) or via LinkedIn (https://www.linkedin.com/in/nhirschfeld/)

Just saw this. Thanks a lot for your code contributions!

**Comment by Goldziher** [comment]
> I understand your concerns regarding the changes made to the codebase, particularly the reversion to JS files and the use of autoimports. Let me clarify the reasons behind these decisions.
> 
> We encountered an issue with vue-i18n where it was causing errors in the browser, preventing the project from loading. The specific error was due to directly importing useI18n() from vue-i18n. This import was not compatible with the current setup, leading to the failure.
> 
> To ensure the project's functionality, we had to revert some changes related to vue-i18n as a temporary solution. We understand this might not be the most elegant solution and could affect tooling and code readability.
> 
> If you have any alternative solutions or are willing to attempt modifying these files again to resolve the issue more effectively, please feel free to make the changes.

Of course, I understand. I suggest adding some issues for fixing these and maybe marking them as good first contributions to the project. 

I would also recommend you make some calls for contributions on Reddit—it has a really nice community for this stuff.

**Pull request merged**
